# Generated by Django 5.0.6 on 2024-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_sales_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-sales_count'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text='Category of the product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Description of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_count',
            field=models.IntegerField(help_text='Number of items available in inventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of items sold'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_50f92a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sales_count'], name='catalog_pro_sales_c_8d5aa7_idx'),
        ),
    ]
